name: Update Maven Version via PR

on:
  push:
    tags:
      - 'v*.*.*' # e.g., v1.2.3

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Update Maven version
        run: mvn versions:set -DnewVersion=${{ env.version }} -DgenerateBackupPoms=false

      - name: Commit changes to a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH="update-version-${{ env.version }}"
          git checkout -b $BRANCH
          git add pom.xml
          git commit -m "chore: update version to ${{ env.version }}"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update version to ${{ env.version }}"
          branch: update-version-${{ env.version }}
          base: main
          title: "Update Maven version to ${{ env.version }}"
          body: "This PR updates the Maven project version to `${{ env.version }}`."
