name: Publish Maven Package on PR Merge

on:
  pull_request:
    types:
      - closed   # Only run when PR is closed
    branches:
      - main     # Only if PR targets main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish to GitHub Packages
        run: mvn clean deploy -DskipTests
